import { Country } from "./types";

export default [
  {
    code: "AF",
    name: "Afghanistan",
    region: "Asia",
    lat: 33.617351,
    lon: 65.03578,
    borders: ["PK", "IR", "TM", "UZ", "TJ", "CN"],
  },
  {
    code: "AX",
    name: "Åland Islands",
    region: "Europe",
    lat: 60.1785,
    lon: 19.9153,
    borders: ["FI"],
  },
  {
    code: "AL",
    name: "Albania",
    region: "Europe",
    lat: 41.1533,
    lon: 20.1683,
    borders: ["ME", "XK", "MK", "GR"],
  },
  {
    code: "DZ",
    name: "Algeria",
    region: "Africa",
    lat: 28.0339,
    lon: 1.6596,
    borders: ["MA", "TN", "LY", "NE", "ML", "MR"],
  },
  {
    code: "AS",
    name: "American Samoa",
    region: "Oceania",
    lat: -14.2708,
    lon: -170.1322,
    borders: [],
  },
  {
    code: "AD",
    name: "Andorra",
    region: "Europe",
    lat: 42.5063,
    lon: 1.5211,
    borders: ["ES", "FR"],
  },
  {
    code: "AO",
    name: "Angola",
    region: "Africa",
    lat: -11.2027,
    lon: 17.8739,
    borders: ["CD", "ZM", "NA", "CG", "GA"],
  },
  {
    code: "AI",
    name: "Anguilla",
    region: "North America",
    lat: 18.2206,
    lon: -63.0686,
    borders: [],
  },
  {
    code: "AQ",
    name: "Antarctica",
    region: "Antarctica",
    lat: -90.0,
    lon: 0.0,
    borders: [],
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    region: "North America",
    lat: 17.0608,
    lon: -61.7964,
    borders: [],
  },
  {
    code: "AR",
    name: "Argentina",
    region: "South America",
    lat: -38.4161,
    lon: -63.6167,
    borders: ["CL", "PY", "BR"],
  },
  {
    code: "AM",
    name: "Armenia",
    region: "Asia",
    lat: 40.0691,
    lon: 45.0382,
    borders: ["GE", "AZ", "IR", "TR"],
  },
  {
    code: "AW",
    name: "Aruba",
    region: "North America",
    lat: 12.5211,
    lon: -69.9683,
    borders: [],
  },
  {
    code: "AU",
    name: "Australia",
    region: "Oceania",
    lat: -25.2744,
    lon: 133.7751,
    borders: [],
  },
  {
    code: "AT",
    name: "Austria",
    region: "Europe",
    lat: 47.5162,
    lon: 14.5501,
    borders: ["DE", "CZ", "SK", "HU", "SI", "IT", "CH"],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    region: "Asia",
    lat: 40.1431,
    lon: 47.5769,
    borders: ["GE", "AM", "IR", "TR", "RU"],
  },
  {
    code: "BS",
    name: "Bahamas",
    region: "North America",
    lat: 25.0343,
    lon: -77.3963,
    borders: [],
  },
  {
    code: "BH",
    name: "Bahrain",
    region: "Asia",
    lat: 25.9304,
    lon: 50.6378,
    borders: ["SA"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    region: "Asia",
    lat: 23.685,
    lon: 90.3563,
    borders: ["MM", "IN"],
  },
  {
    code: "BB",
    name: "Barbados",
    region: "North America",
    lat: 13.1939,
    lon: -59.5432,
    borders: [],
  },
  {
    code: "BY",
    name: "Belarus",
    region: "Europe",
    lat: 53.9045,
    lon: 27.559,
    borders: ["LT", "LV", "RU", "UA", "PL"],
  },
  {
    code: "BE",
    name: "Belgium",
    region: "Europe",
    lat: 50.8503,
    lon: 4.3517,
    borders: ["FR", "DE", "NL", "LU"],
  },
  {
    code: "BZ",
    name: "Belize",
    region: "North America",
    lat: 17.1899,
    lon: -88.4976,
    borders: ["GT", "MX"],
  },
  {
    code: "BJ",
    name: "Benin",
    region: "Africa",
    lat: 9.3077,
    lon: 2.3158,
    borders: ["TG", "NG", "BF", "NE"],
  },
  {
    code: "BM",
    name: "Bermuda",
    region: "North America",
    lat: 32.3214,
    lon: -64.7574,
    borders: [],
  },
  {
    code: "BT",
    name: "Bhutan",
    region: "Asia",
    lat: 27.5149,
    lon: 90.4336,
    borders: ["IN", "CN"],
  },
  {
    code: "BO",
    name: "Bolivia (Plurinational State of)",
    region: "South America",
    lat: -16.2902,
    lon: -63.5887,
    borders: ["PE", "BR", "PY", "AR", "CL"],
  },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    region: "North America",
    lat: 12.1784,
    lon: -68.2385,
    borders: [],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    region: "Europe",
    lat: 43.9159,
    lon: 17.6791,
    borders: ["HR", "RS", "ME"],
  },
  {
    code: "BW",
    name: "Botswana",
    region: "Africa",
    lat: -22.3285,
    lon: 24.6849,
    borders: ["NA", "ZA", "ZW"],
  },
  {
    code: "BV",
    name: "Bouvet Island",
    region: "Antarctica",
    lat: -54.4222,
    lon: 3.3464,
    borders: [],
  },
  {
    code: "BR",
    name: "Brazil",
    region: "South America",
    lat: -14.235,
    lon: -51.9253,
    borders: ["AR", "BO", "PY", "UY", "VE", "GY", "SR", "CO", "PE", "CL"],
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    region: "Asia",
    lat: -6.3432,
    lon: 71.8767,
    borders: [],
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    region: "Asia",
    lat: 4.5353,
    lon: 114.7277,
    borders: ["MY"],
  },
  {
    code: "BG",
    name: "Bulgaria",
    region: "Europe",
    lat: 42.7339,
    lon: 25.4858,
    borders: ["RO", "HU", "RS", "MK", "GR", "TR"],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    region: "Africa",
    lat: 12.2383,
    lon: -1.5616,
    borders: ["NE", "BJ", "TG", "GH", "CI"],
  },
  {
    code: "BI",
    name: "Burundi",
    region: "Africa",
    lat: -3.3731,
    lon: 29.9189,
    borders: ["RW", "TZ", "CD"],
  },
  {
    code: "CV",
    name: "Cabo Verde",
    region: "Africa",
    lat: 16.0021,
    lon: -24.0132,
    borders: [],
  },
  {
    code: "KH",
    name: "Cambodia",
    region: "Asia",
    lat: 12.5657,
    lon: 104.991,
    borders: ["TH", "LA", "VN"],
  },
  {
    code: "CM",
    name: "Cameroon",
    region: "Africa",
    lat: 3.848,
    lon: 11.5021,
    borders: ["NG", "TD", "CF", "CG", "GQ", "GA"],
  },
  {
    code: "CA",
    name: "Canada",
    region: "North America",
    lat: 56.1304,
    lon: -106.3468,
    borders: ["US"],
  },
  {
    code: "KY",
    name: "Cayman Islands",
    region: "North America",
    lat: 19.3133,
    lon: -81.2546,
    borders: [],
  },
  {
    code: "CF",
    name: "Central African Republic",
    region: "Africa",
    lat: 6.6111,
    lon: 20.9394,
    borders: ["TD", "SD", "CD", "CG", "GA"],
  },
  {
    code: "TD",
    name: "Chad",
    region: "Africa",
    lat: 15.4542,
    lon: 18.7322,
    borders: ["LY", "NE", "CM", "NG", "CF"],
  },
  {
    code: "CL",
    name: "Chile",
    region: "South America",
    lat: -35.6751,
    lon: -71.543,
    borders: ["AR", "BO", "PE"],
  },
  {
    code: "CN",
    name: "China",
    region: "Asia",
    lat: 35.8617,
    lon: 104.1954,
    borders: [
      "MN",
      "RU",
      "KZ",
      "TJ",
      "KG",
      "UZ",
      "AF",
      "NP",
      "BT",
      "IN",
      "MM",
      "LA",
      "VN",
      "KH",
    ],
  },
  {
    code: "CX",
    name: "Christmas Island",
    region: "Oceania",
    lat: -10.4475,
    lon: 105.6904,
    borders: [],
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    region: "Oceania",
    lat: -12.1642,
    lon: 96.8709,
    borders: [],
  },
  {
    code: "CO",
    name: "Colombia",
    region: "South America",
    lat: 4.5709,
    lon: -74.2973,
    borders: ["PA", "VE", "BR", "PY", "PE"],
  },
  {
    code: "KM",
    name: "Comoros",
    region: "Africa",
    lat: -11.875,
    lon: 43.8722,
    borders: [],
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    region: "Africa",
    lat: -4.0383,
    lon: 21.7587,
    borders: [
      "CG",
      "GA",
      "CM",
      "TD",
      "CF",
      "SS",
      "RW",
      "BI",
      "TZ",
      "ZM",
      "ANG",
    ],
  },
  {
    code: "CG",
    name: "Congo",
    region: "Africa",
    lat: -0.228,
    lon: 15.8277,
    borders: ["GA", "CM", "CD", "CF"],
  },
  {
    code: "CK",
    name: "Cook Islands",
    region: "Oceania",
    lat: -21.2362,
    lon: -159.7777,
    borders: [],
  },
  {
    code: "CR",
    name: "Costa Rica",
    region: "North America",
    lat: 9.7489,
    lon: -83.7534,
    borders: ["NI", "PA"],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    region: "Africa",
    lat: 7.5399,
    lon: -5.5471,
    borders: ["GH", "BJ", "TG", "BF", "ML"],
  },
  {
    code: "HR",
    name: "Croatia",
    region: "Europe",
    lat: 45.1,
    lon: 15.2,
    borders: ["SI", "HU", "RS", "BA", "ME"],
  },
  {
    code: "CU",
    name: "Cuba",
    region: "North America",
    lat: 21.5216,
    lon: -77.7812,
    borders: [],
  },
  {
    code: "CW",
    name: "Curaçao",
    region: "North America",
    lat: 12.1696,
    lon: -68.99,
    borders: [],
  },
  {
    code: "CY",
    name: "Cyprus",
    region: "Asia",
    lat: 35.1264,
    lon: 33.4299,
    borders: ["TR"],
  },
  {
    code: "CZ",
    name: "Czechia",
    region: "Europe",
    lat: 49.8175,
    lon: 15.473,
    borders: ["DE", "PL", "SK", "AT"],
  },
  {
    code: "DK",
    name: "Denmark",
    region: "Europe",
    lat: 56.2639,
    lon: 9.5018,
    borders: ["DE", "SE"],
  },
  {
    code: "DJ",
    name: "Djibouti",
    region: "Africa",
    lat: 11.8251,
    lon: 42.5903,
    borders: ["ET", "SO", "ER"],
  },
  {
    code: "DM",
    name: "Dominica",
    region: "North America",
    lat: 15.4149,
    lon: -61.3709,
    borders: [],
  },
  {
    code: "DO",
    name: "Dominican Republic",
    region: "North America",
    lat: 18.7359,
    lon: -70.1627,
    borders: ["HT"],
  },
  {
    code: "EC",
    name: "Ecuador",
    region: "South America",
    lat: -1.8312,
    lon: -78.1834,
    borders: ["CO", "PE"],
  },
  {
    code: "EG",
    name: "Egypt",
    region: "Africa",
    lat: 26.8206,
    lon: 30.8025,
    borders: ["LY", "SD", "IL", "PS"],
  },
  {
    code: "SV",
    name: "El Salvador",
    region: "North America",
    lat: 13.7942,
    lon: -88.8965,
    borders: ["HN", "GT"],
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    region: "Africa",
    lat: 1.6508,
    lon: 10.2679,
    borders: ["CM", "GA"],
  },
  {
    code: "ER",
    name: "Eritrea",
    region: "Africa",
    lat: 15.1792,
    lon: 39.7823,
    borders: ["SD", "DJ", "ET"],
  },
  {
    code: "EE",
    name: "Estonia",
    region: "Europe",
    lat: 58.5953,
    lon: 25.0136,
    borders: ["LV", "RU"],
  },
  {
    code: "SZ",
    name: "Eswatini",
    region: "Africa",
    lat: -26.5225,
    lon: 31.4659,
    borders: ["ZA", "MZ"],
  },
  {
    code: "ET",
    name: "Ethiopia",
    region: "Africa",
    lat: 9.145,
    lon: 40.489673,
    borders: ["DJ", "ER", "SO", "KE", "SS", "SD"],
  },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    region: "South America",
    lat: -51.7963,
    lon: -59.5236,
    borders: [],
  },
  {
    code: "FO",
    name: "Faroe Islands",
    region: "Europe",
    lat: 61.8926,
    lon: -6.9118,
    borders: ["DK"],
  },
  {
    code: "FJ",
    name: "Fiji",
    region: "Oceania",
    lat: -17.7134,
    lon: 178.065,
    borders: [],
  },
  {
    code: "FI",
    name: "Finland",
    region: "Europe",
    lat: 61.9241,
    lon: 25.7482,
    borders: ["NO", "SE", "RU"],
  },
  {
    code: "FR",
    name: "France",
    region: "Europe",
    lat: 46.6034,
    lon: 1.8883,
    borders: ["BE", "DE", "LU", "CH", "IT", "MC", "ES", "AD"],
  },
  {
    code: "GF",
    name: "French Guiana",
    region: "South America",
    lat: 3.9339,
    lon: -53.1258,
    borders: ["BR", "SR"],
  },
  {
    code: "PF",
    name: "French Polynesia",
    region: "Oceania",
    lat: -17.6797,
    lon: -149.4068,
    borders: [],
  },
  {
    code: "TF",
    name: "French Southern Territories",
    region: "Antarctica",
    lat: -49.2804,
    lon: 69.3485,
    borders: [],
  },
  {
    code: "GA",
    name: "Gabon",
    region: "Africa",
    lat: -0.8031,
    lon: 11.6094,
    borders: ["CM", "GQ", "CG"],
  },
  {
    code: "GM",
    name: "Gambia",
    region: "Africa",
    lat: 13.4432,
    lon: -15.3101,
    borders: ["SN"],
  },
  {
    code: "GE",
    name: "Georgia",
    region: "Asia",
    lat: 42.3154,
    lon: 43.3569,
    borders: ["RU", "AM", "AZ", "TR"],
  },
  {
    code: "DE",
    name: "Germany",
    region: "Europe",
    lat: 51.1657,
    lon: 10.4515,
    borders: ["DK", "PL", "CZ", "AT", "CH", "FR", "LU", "BE", "NL"],
  },
  {
    code: "GH",
    name: "Ghana",
    region: "Africa",
    lat: 7.5399,
    lon: -0.205,
    borders: ["CI", "BJ", "TG"],
  },
  {
    code: "GI",
    name: "Gibraltar",
    region: "Europe",
    lat: 36.1408,
    lon: -5.3536,
    borders: ["ES"],
  },
  {
    code: "GR",
    name: "Greece",
    region: "Europe",
    lat: 39.0742,
    lon: 21.8243,
    borders: ["AL", "MK", "BG", "TR"],
  },
  {
    code: "GL",
    name: "Greenland",
    region: "North America",
    lat: 71.7069,
    lon: -42.6043,
    borders: [],
  },
  {
    code: "GD",
    name: "Grenada",
    region: "North America",
    lat: 12.2628,
    lon: -61.6042,
    borders: [],
  },
  {
    code: "GP",
    name: "Guadeloupe",
    region: "North America",
    lat: 16.9959,
    lon: -62.0675,
    borders: [],
  },
  {
    code: "GU",
    name: "Guam",
    region: "Oceania",
    lat: 13.4443,
    lon: 144.7937,
    borders: [],
  },
  {
    code: "GT",
    name: "Guatemala",
    region: "North America",
    lat: 15.7835,
    lon: -90.2308,
    borders: ["BZ", "MX", "HN"],
  },
  {
    code: "GG",
    name: "Guernsey",
    region: "Europe",
    lat: 49.4657,
    lon: -2.5853,
    borders: ["JE"],
  },
  {
    code: "GN",
    name: "Guinea",
    region: "Africa",
    lat: 9.9456,
    lon: -9.6966,
    borders: ["SN", "GM", "CI", "LR"],
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    region: "Africa",
    lat: 11.8037,
    lon: -15.1804,
    borders: ["SN", "GW"],
  },
  {
    code: "GY",
    name: "Guyana",
    region: "South America",
    lat: 4.8604,
    lon: -58.9302,
    borders: ["VE", "BR", "SR"],
  },
  {
    code: "HT",
    name: "Haiti",
    region: "North America",
    lat: 18.9712,
    lon: -72.2851,
    borders: ["DO"],
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    region: "Antarctica",
    lat: -53.0818,
    lon: 73.5042,
    borders: [],
  },
  {
    code: "VA",
    name: "Holy See",
    region: "Europe",
    lat: 41.9029,
    lon: 12.4534,
    borders: ["IT"],
  },
  {
    code: "HN",
    name: "Honduras",
    region: "North America",
    lat: 15.1999,
    lon: -86.2419,
    borders: ["GTM", "SV", "NI"],
  },
  {
    code: "HK",
    name: "Hong Kong",
    region: "Asia",
    lat: 22.3964,
    lon: 114.1095,
    borders: ["CN"],
  },
  {
    code: "HU",
    name: "Hungary",
    region: "Europe",
    lat: 47.1625,
    lon: 19.5033,
    borders: ["SK", "UA", "RO", "RS", "SI", "AT"],
  },
  {
    code: "IS",
    name: "Iceland",
    region: "Europe",
    lat: 64.9631,
    lon: -19.0208,
    borders: [],
  },
  {
    code: "IN",
    name: "India",
    region: "Asia",
    lat: 20.5937,
    lon: 78.9629,
    borders: ["CN", "NP", "BT", "BD", "MM", "LK", "PK", "AF", "MV", "TL", "TL"],
  },
  {
    code: "ID",
    name: "Indonesia",
    region: "Asia",
    lat: -0.7893,
    lon: 113.9213,
    borders: ["TL", "PG"],
  },
  {
    code: "IR",
    name: "Iran (Islamic Republic of)",
    region: "Asia",
    lat: 32.4279,
    lon: 53.688,
    borders: ["TR", "AM", "AZ", "AF", "PK", "IQ"],
  },
  {
    code: "IQ",
    name: "Iraq",
    region: "Asia",
    lat: 33.2232,
    lon: 43.6793,
    borders: ["TR", "IR", "AF", "SY", "JO", "KW"],
  },
  {
    code: "IE",
    name: "Ireland",
    region: "Europe",
    lat: 53.4129,
    lon: -8.2439,
    borders: ["GB"],
  },
  {
    code: "IM",
    name: "Isle of Man",
    region: "Europe",
    lat: 54.2361,
    lon: -4.5481,
    borders: ["GB"],
  },
  {
    code: "IL",
    name: "Israel",
    region: "Asia",
    lat: 31.0461,
    lon: 34.8516,
    borders: ["LB", "SY", "JO", "PS", "EG"],
  },
  {
    code: "IT",
    name: "Italy",
    region: "Europe",
    lat: 41.8719,
    lon: 12.5674,
    borders: ["FR", "CH", "AT", "SI", "SM", "VA"],
  },
  {
    code: "JM",
    name: "Jamaica",
    region: "North America",
    lat: 18.1096,
    lon: -77.2975,
    borders: [],
  },
  {
    code: "JP",
    name: "Japan",
    region: "Asia",
    lat: 36.2048,
    lon: 138.2529,
    borders: [],
  },
  {
    code: "JE",
    name: "Jersey",
    region: "Europe",
    lat: 49.2144,
    lon: -2.1312,
    borders: ["GB"],
  },
  {
    code: "JO",
    name: "Jordan",
    region: "Asia",
    lat: 30.5852,
    lon: 36.2384,
    borders: ["SY", "IQ", "SA", "PS"],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    region: "Asia",
    lat: 48.0196,
    lon: 66.9237,
    borders: ["RU", "MN", "CN", "KG", "UZ", "TM"],
  },
  {
    code: "KE",
    name: "Kenya",
    region: "Africa",
    lat: -0.0236,
    lon: 37.9062,
    borders: ["ET", "SO", "TZ", "UG", "SS"],
  },
  {
    code: "KI",
    name: "Kiribati",
    region: "Oceania",
    lat: -3.3704,
    lon: -168.734,
    borders: [],
  },
  {
    code: "KP",
    name: "Korea (Democratic People's Republic of)",
    region: "Asia",
    lat: 40.3399,
    lon: 127.5101,
    borders: ["CN", "RU", "KR"],
  },
  {
    code: "KR",
    name: "Korea, Republic of",
    region: "Asia",
    lat: 35.9078,
    lon: 127.7669,
    borders: ["KP"],
  },
  {
    code: "KW",
    name: "Kuwait",
    region: "Asia",
    lat: 29.3117,
    lon: 47.4818,
    borders: ["SA", "IQ"],
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    region: "Asia",
    lat: 41.2044,
    lon: 74.7661,
    borders: ["KZ", "UZ", "TJ", "CN"],
  },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    region: "Asia",
    lat: 19.8563,
    lon: 102.4955,
    borders: ["CN", "MM", "TH", "KH", "VN"],
  },
  {
    code: "LV",
    name: "Latvia",
    region: "Europe",
    lat: 56.8796,
    lon: 24.6032,
    borders: ["LT", "BY", "RU", "EE"],
  },
  {
    code: "LB",
    name: "Lebanon",
    region: "Asia",
    lat: 33.8547,
    lon: 35.8623,
    borders: ["SY", "IL"],
  },
  {
    code: "LS",
    name: "Lesotho",
    region: "Africa",
    lat: -29.6099,
    lon: 28.2336,
    borders: ["ZA"],
  },
  {
    code: "LR",
    name: "Liberia",
    region: "Africa",
    lat: 6.4281,
    lon: -9.4295,
    borders: ["SL", "GN", "CI"],
  },
  {
    code: "LY",
    name: "Libya",
    region: "Africa",
    lat: 26.3351,
    lon: 17.2288,
    borders: ["TN", "DZ", "NE", "SD", "CH"],
  },
  {
    code: "LI",
    name: "Liechtenstein",
    region: "Europe",
    lat: 47.166,
    lon: 9.5554,
    borders: ["CH", "AT"],
  },
  {
    code: "LT",
    name: "Lithuania",
    region: "Europe",
    lat: 55.1694,
    lon: 23.8813,
    borders: ["LV", "BY", "PL", "RU"],
  },
  {
    code: "LU",
    name: "Luxembourg",
    region: "Europe",
    lat: 49.6118,
    lon: 6.1319,
    borders: ["BE", "DE", "FR"],
  },
  {
    code: "MO",
    name: "Macao",
    region: "Asia",
    lat: 22.1987,
    lon: 113.5439,
    borders: ["CN"],
  },
  {
    code: "MG",
    name: "Madagascar",
    region: "Africa",
    lat: -18.7669,
    lon: 46.8691,
    borders: [],
  },
  {
    code: "MW",
    name: "Malawi",
    region: "Africa",
    lat: -13.2543,
    lon: 34.3015,
    borders: ["TZ", "ZM", "MZ"],
  },
  {
    code: "MY",
    name: "Malaysia",
    region: "Asia",
    lat: 4.2105,
    lon: 101.9758,
    borders: ["TH", "SG", "ID"],
  },
  {
    code: "MV",
    name: "Maldives",
    region: "Asia",
    lat: 3.2028,
    lon: 73.2207,
    borders: [],
  },
  {
    code: "ML",
    name: "Mali",
    region: "Africa",
    lat: 17.5707,
    lon: -3.9962,
    borders: ["SN", "GN", "CI", "BF", "NE", "DZ"],
  },
  {
    code: "MT",
    name: "Malta",
    region: "Europe",
    lat: 35.9375,
    lon: 14.3754,
    borders: [],
  },
  {
    code: "MH",
    name: "Marshall Islands",
    region: "Oceania",
    lat: 7.1095,
    lon: 171.184,
    borders: [],
  },
  {
    code: "MQ",
    name: "Martinique",
    region: "North America",
    lat: 14.6415,
    lon: -61.0242,
    borders: [],
  },
  {
    code: "MR",
    name: "Mauritania",
    region: "Africa",
    lat: 20.254,
    lon: -10.1856,
    borders: ["MA", "DZ", "ML", "SN", "GN"],
  },
  {
    code: "MU",
    name: "Mauritius",
    region: "Africa",
    lat: -20.348404,
    lon: 57.552152,
    borders: [],
  },
  {
    code: "YT",
    name: "Mayotte",
    region: "Africa",
    lat: -12.8275,
    lon: 45.1662,
    borders: ["MG"],
  },
  {
    code: "MX",
    name: "Mexico",
    region: "North America",
    lat: 23.6345,
    lon: -102.5528,
    borders: ["US", "BZ", "GT"],
  },
  {
    code: "FM",
    name: "Micronesia (Federated States of)",
    region: "Oceania",
    lat: 7.4256,
    lon: 150.5508,
    borders: [],
  },
  {
    code: "MD",
    name: "Moldova (Republic of)",
    region: "Europe",
    lat: 47.4116,
    lon: 28.3699,
    borders: ["UA", "RO"],
  },
  {
    code: "MC",
    name: "Monaco",
    region: "Europe",
    lat: 43.7384,
    lon: 7.4246,
    borders: ["FR"],
  },
  {
    code: "MN",
    name: "Mongolia",
    region: "Asia",
    lat: 46.8625,
    lon: 103.8467,
    borders: ["RU", "CN"],
  },
  {
    code: "ME",
    name: "Montenegro",
    region: "Europe",
    lat: 42.7087,
    lon: 19.3744,
    borders: ["HR", "BA", "RS", "XK"],
  },
  {
    code: "MS",
    name: "Montserrat",
    region: "North America",
    lat: 16.7425,
    lon: -62.1874,
    borders: [],
  },
  {
    code: "MA",
    name: "Morocco",
    region: "Africa",
    lat: 31.7917,
    lon: -7.0926,
    borders: ["DZ", "EH"],
  },
  {
    code: "MZ",
    name: "Mozambique",
    region: "Africa",
    lat: -18.6657,
    lon: 35.5299,
    borders: ["ZA", "SZ", "TZ", "MW", "ZM", "CD"],
  },
  {
    code: "MM",
    name: "Myanmar",
    region: "Asia",
    lat: 21.9162,
    lon: 95.956,
    borders: ["CN", "LA", "TH", "BD"],
  },
  {
    code: "NA",
    name: "Namibia",
    region: "Africa",
    lat: -22.9576,
    lon: 18.4904,
    borders: ["ZA", "BW", "ZM", "AO"],
  },
  {
    code: "NR",
    name: "Nauru",
    region: "Oceania",
    lat: -0.5228,
    lon: 166.9315,
    borders: [],
  },
  {
    code: "NP",
    name: "Nepal",
    region: "Asia",
    lat: 28.3949,
    lon: 84.124,
    borders: ["CN", "IN"],
  },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe",
    lat: 52.1326,
    lon: 5.2913,
    borders: ["BE", "DE"],
  },
  {
    code: "NC",
    name: "New Caledonia",
    region: "Oceania",
    lat: -20.9043,
    lon: 165.618,
    borders: [],
  },
  {
    code: "NZ",
    name: "New Zealand",
    region: "Oceania",
    lat: -40.9006,
    lon: 174.886,
    borders: [],
  },
  {
    code: "NI",
    name: "Nicaragua",
    region: "North America",
    lat: 12.8654,
    lon: -85.2072,
    borders: ["HN", "CR"],
  },
  {
    code: "NE",
    name: "Niger",
    region: "Africa",
    lat: 17.6078,
    lon: 8.0817,
    borders: ["LY", "DZ", "MA", "ML", "BF", "GH", "BJ", "NG"],
  },
  {
    code: "NG",
    name: "Nigeria",
    region: "Africa",
    lat: 9.082,
    lon: 8.6753,
    borders: ["BJ", "NE", "CM", "TD"],
  },
  {
    code: "NU",
    name: "Niue",
    region: "Oceania",
    lat: -19.0544,
    lon: -169.8671,
    borders: [],
  },
  {
    code: "NF",
    name: "Norfolk Island",
    region: "Oceania",
    lat: -29.0405,
    lon: 167.9547,
    borders: [],
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    region: "Oceania",
    lat: 14.7946,
    lon: 145.7505,
    borders: [],
  },
  {
    code: "NO",
    name: "Norway",
    region: "Europe",
    lat: 60.472,
    lon: 8.4689,
    borders: ["SE", "FI", "RU"],
  },
  {
    code: "OM",
    name: "Oman",
    region: "Asia",
    lat: 21.5126,
    lon: 55.9233,
    borders: ["YE", "AE", "SA", "IQ"],
  },
  {
    code: "PK",
    name: "Pakistan",
    region: "Asia",
    lat: 30.3753,
    lon: 69.3451,
    borders: ["AF", "CN", "IN", "IR"],
  },
  {
    code: "PW",
    name: "Palau",
    region: "Oceania",
    lat: 7.5149,
    lon: 134.5825,
    borders: [],
  },
  {
    code: "PS",
    name: "Palestine, State of",
    region: "Asia",
    lat: 31.9522,
    lon: 35.2332,
    borders: ["IL", "JO"],
  },
  {
    code: "PA",
    name: "Panama",
    region: "North America",
    lat: 8.5379,
    lon: -80.7821,
    borders: ["CR", "CO"],
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    region: "Oceania",
    lat: -6.314,
    lon: 143.9555,
    borders: ["ID"],
  },
  {
    code: "PY",
    name: "Paraguay",
    region: "South America",
    lat: -23.4422,
    lon: -58.4438,
    borders: ["AR", "BR", "PY"],
  },
  {
    code: "PE",
    name: "Peru",
    region: "South America",
    lat: -9.19,
    lon: -75.0152,
    borders: ["EC", "CO", "BR", "BO", "CL"],
  },
  {
    code: "PH",
    name: "Philippines",
    region: "Asia",
    lat: 12.8797,
    lon: 121.774,
    borders: [],
  },
  {
    code: "PN",
    name: "Pitcairn",
    region: "Oceania",
    lat: -24.7036,
    lon: -127.4398,
    borders: [],
  },
  {
    code: "PL",
    name: "Poland",
    region: "Europe",
    lat: 51.9194,
    lon: 19.1451,
    borders: ["DE", "CZ", "SK", "UA", "BY", "LT", "RU"],
  },
  {
    code: "PT",
    name: "Portugal",
    region: "Europe",
    lat: 39.3999,
    lon: -8.2245,
    borders: ["ES"],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    region: "North America",
    lat: 18.2208,
    lon: -66.5901,
    borders: [],
  },
  {
    code: "QA",
    name: "Qatar",
    region: "Asia",
    lat: 25.276987,
    lon: 51.520008,
    borders: ["SA", "BH"],
  },
  {
    code: "RE",
    name: "Réunion",
    region: "Africa",
    lat: -21.1151,
    lon: 55.5364,
    borders: [],
  },
  {
    code: "RO",
    name: "Romania",
    region: "Europe",
    lat: 45.9432,
    lon: 24.9668,
    borders: ["UA", "MD", "HU", "RS", "BG"],
  },
  {
    code: "RU",
    name: "Russian Federation",
    region: "Asia",
    lat: 62.806,
    lon: 90.5,
    borders: [
      "NO",
      "FI",
      "EE",
      "LV",
      "LT",
      "BY",
      "UA",
      "MD",
      "GE",
      "AM",
      "AZ",
      "KZ",
      "MN",
      "CN",
      "KG",
      "TJ",
      "UZ",
      "TM",
      "KP",
      "JP",
      "KR",
    ],
  },
  {
    code: "RW",
    name: "Rwanda",
    region: "Africa",
    lat: -1.9403,
    lon: 29.8739,
    borders: ["UG", "TZ", "BI", "CD"],
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    region: "North America",
    lat: 17.9,
    lon: -62.85,
    borders: [],
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    region: "Africa",
    lat: -15.9654,
    lon: -5.7009,
    borders: [],
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    region: "North America",
    lat: 17.357822,
    lon: -62.782998,
    borders: [],
  },
  {
    code: "LC",
    name: "Saint Lucia",
    region: "North America",
    lat: 13.9094,
    lon: -60.9789,
    borders: [],
  },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    region: "North America",
    lat: 18.0708,
    lon: -63.0849,
    borders: [],
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    region: "North America",
    lat: 46.8255,
    lon: -56.3747,
    borders: [],
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    region: "North America",
    lat: 12.9843,
    lon: -61.2872,
    borders: [],
  },
  {
    code: "WS",
    name: "Samoa",
    region: "Oceania",
    lat: -13.759,
    lon: -172.1046,
    borders: [],
  },
  {
    code: "SM",
    name: "San Marino",
    region: "Europe",
    lat: 43.9333,
    lon: 12.4467,
    borders: ["IT"],
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    region: "Africa",
    lat: 0.1864,
    lon: 6.6131,
    borders: [],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    region: "Asia",
    lat: 23.8859,
    lon: 45.0792,
    borders: ["YE", "OM", "AE", "QA", "BH", "KW", "IQ", "JO"],
  },
  {
    code: "SN",
    name: "Senegal",
    region: "Africa",
    lat: 14.4974,
    lon: -14.4524,
    borders: ["MR", "ML", "GN", "GQ", "GW", "BJ"],
  },
  {
    code: "RS",
    name: "Serbia",
    region: "Europe",
    lat: 44.0165,
    lon: 21.0059,
    borders: ["HU", "RO", "BG", "MK", "AL", "ME", "HR"],
  },
  {
    code: "SC",
    name: "Seychelles",
    region: "Africa",
    lat: -4.6796,
    lon: 55.4911,
    borders: [],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    region: "Africa",
    lat: 8.4606,
    lon: -11.7799,
    borders: ["GN", "LR"],
  },
  {
    code: "SG",
    name: "Singapore",
    region: "Asia",
    lat: 1.3521,
    lon: 103.8198,
    borders: ["MY"],
  },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    region: "North America",
    lat: 18.0425,
    lon: -63.0581,
    borders: [],
  },
  {
    code: "SK",
    name: "Slovakia",
    region: "Europe",
    lat: 48.669,
    lon: 19.699,
    borders: ["CZ", "PL", "UA", "HU", "AT"],
  },
  {
    code: "SI",
    name: "Slovenia",
    region: "Europe",
    lat: 46.1512,
    lon: 14.9955,
    borders: ["IT", "AT", "HU", "HR"],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    region: "Oceania",
    lat: -9.428,
    lon: 160.0,
    borders: [],
  },
  {
    code: "SO",
    name: "Somalia",
    region: "Africa",
    lat: 5.1521,
    lon: 46.1996,
    borders: ["DJ", "ET", "KE"],
  },
  {
    code: "ZA",
    name: "South Africa",
    region: "Africa",
    lat: -30.5595,
    lon: 22.9375,
    borders: ["NA", "BW", "SZ", "MZ", "LS", "ZA"],
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    region: "Antarctica",
    lat: -54.4296,
    lon: -36.5879,
    borders: [],
  },
  {
    code: "SS",
    name: "South Sudan",
    region: "Africa",
    lat: 6.877,
    lon: 31.3069,
    borders: ["ET", "SD", "UG", "KE"],
  },
  {
    code: "ES",
    name: "Spain",
    region: "Europe",
    lat: 40.4637,
    lon: -3.7492,
    borders: ["PT", "FR", "AD", "GI"],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    region: "Asia",
    lat: 7.8731,
    lon: 80.7718,
    borders: [],
  },
  {
    code: "SD",
    name: "Sudan",
    region: "Africa",
    lat: 12.8628,
    lon: 30.2176,
    borders: ["EG", "LY", "TD", "CM", "NG", "SS"],
  },
  {
    code: "SR",
    name: "Suriname",
    region: "South America",
    lat: 3.9193,
    lon: -56.0275,
    borders: ["GF", "BR", "GY"],
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    region: "Europe",
    lat: 77.5535,
    lon: 23.6704,
    borders: [],
  },
  {
    code: "SE",
    name: "Sweden",
    region: "Europe",
    lat: 60.1282,
    lon: 18.6435,
    borders: ["NO", "FI", "DK"],
  },
  {
    code: "CH",
    name: "Switzerland",
    region: "Europe",
    lat: 46.8182,
    lon: 8.2275,
    borders: ["DE", "FR", "IT", "LI", "AT"],
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    region: "Asia",
    lat: 34.8021,
    lon: 38.9968,
    borders: ["TR", "IQ", "JO", "IL", "LB"],
  },
  {
    code: "TW",
    name: "Taiwan, Province of China",
    region: "Asia",
    lat: 23.6978,
    lon: 120.9605,
    borders: [],
  },
  {
    code: "TJ",
    name: "Tajikistan",
    region: "Asia",
    lat: 38.861,
    lon: 71.2761,
    borders: ["UZ", "KG", "CN", "AF"],
  },
  {
    code: "TZ",
    name: "Tanzania, United Republic of",
    region: "Africa",
    lat: -6.369,
    lon: 34.8888,
    borders: ["KE", "UG", "RW", "BI", "CD", "ZM", "MW", "MZ"],
  },
  {
    code: "TH",
    name: "Thailand",
    region: "Asia",
    lat: 15.8701,
    lon: 100.9925,
    borders: ["MM", "LA", "KH", "MY"],
  },
  {
    code: "TL",
    name: "Timor-Leste",
    region: "Asia",
    lat: -8.8749,
    lon: 125.7275,
    borders: ["ID"],
  },
  {
    code: "TG",
    name: "Togo",
    region: "Africa",
    lat: 8.6195,
    lon: 0.8248,
    borders: ["BJ", "GH", "BF"],
  },
  {
    code: "TK",
    name: "Tokelau",
    region: "Oceania",
    lat: -9.2002,
    lon: -171.8571,
    borders: [],
  },
  {
    code: "TO",
    name: "Tonga",
    region: "Oceania",
    lat: -21.1789,
    lon: -175.1982,
    borders: [],
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    region: "North America",
    lat: 10.6918,
    lon: -61.2225,
    borders: [],
  },
  {
    code: "TN",
    name: "Tunisia",
    region: "Africa",
    lat: 33.8869,
    lon: 9.5375,
    borders: ["DZ", "LY"],
  },
  {
    code: "TR",
    name: "Turkey",
    region: "Asia",
    lat: 38.9637,
    lon: 35.2433,
    borders: ["BG", "GR", "GE", "AM", "AZ", "IR", "IQ", "SY"],
  },
  {
    code: "TM",
    name: "Turkmenistan",
    region: "Asia",
    lat: 35.8617,
    lon: 59.5563,
    borders: ["KZ", "UZ", "AF", "IR"],
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    region: "North America",
    lat: 21.6949,
    lon: -71.7979,
    borders: [],
  },
  {
    code: "TV",
    name: "Tuvalu",
    region: "Oceania",
    lat: -7.1095,
    lon: 179.1945,
    borders: [],
  },
  {
    code: "UG",
    name: "Uganda",
    region: "Africa",
    lat: 1.3733,
    lon: 32.2903,
    borders: ["SS", "KE", "TZ", "RW", "CD"],
  },
  {
    code: "UA",
    name: "Ukraine",
    region: "Europe",
    lat: 48.3794,
    lon: 31.1656,
    borders: ["BY", "RU", "MD", "RO", "HU", "SK", "PL"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Asia",
    lat: 23.4241,
    lon: 53.8478,
    borders: ["OM", "SA"],
  },
  {
    code: "GB",
    name: "United Kingdom of Great Britain and Northern Ireland",
    region: "Europe",
    lat: 55.3781,
    lon: -3.436,
    borders: ["IE"],
  },
  {
    code: "US",
    name: "United States of America",
    region: "North America",
    lat: 37.0902,
    lon: -95.7129,
    borders: ["CA", "MX"],
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    region: "North America",
    lat: -0.7893,
    lon: -170.0982,
    borders: [],
  },
  {
    code: "UY",
    name: "Uruguay",
    region: "South America",
    lat: -32.5228,
    lon: -55.7658,
    borders: ["BR", "AR"],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    region: "Asia",
    lat: 41.3775,
    lon: 64.5853,
    borders: ["KZ", "KG", "TJ", "TM", "AF"],
  },
  {
    code: "VU",
    name: "Vanuatu",
    region: "Oceania",
    lat: -15.3767,
    lon: 166.9592,
    borders: [],
  },
  {
    code: "VE",
    name: "Venezuela (Bolivarian Republic of)",
    region: "South America",
    lat: 6.4238,
    lon: -66.5897,
    borders: ["CO", "BR", "GY"],
  },
  {
    code: "VN",
    name: "Viet Nam",
    region: "Asia",
    lat: 14.0583,
    lon: 108.2772,
    borders: ["CN", "LA", "KH"],
  },
  {
    code: "VG",
    name: "Virgin Islands (British)",
    region: "North America",
    lat: 18.4207,
    lon: -64.6399,
    borders: [],
  },
  {
    code: "VI",
    name: "Virgin Islands (U.S.)",
    region: "North America",
    lat: 18.3358,
    lon: -64.8963,
    borders: [],
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    region: "Oceania",
    lat: -13.7687,
    lon: -178.1659,
    borders: [],
  },
  {
    code: "EH",
    name: "Western Sahara",
    region: "Africa",
    lat: 24.2155,
    lon: -12.8858,
    borders: ["MA", "DZ", "ML"],
  },
  {
    code: "YE",
    name: "Yemen",
    region: "Asia",
    lat: 15.5526,
    lon: 48.5164,
    borders: ["OM", "SA"],
  },
  {
    code: "ZM",
    name: "Zambia",
    region: "Africa",
    lat: -13.1339,
    lon: 27.8493,
    borders: ["CD", "ML", "MW", "TZ", "ZW", "NA", "BW"],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    region: "Africa",
    lat: -19.0154,
    lon: 29.1549,
    borders: ["ZA", "BW", "ZM"],
  },
] as Country[];
